<table>
<tr>
<td>{group:galaxy_row:row_position}</td>
<td>{group:galaxy_row:row_planet}</td>
<td>{group:galaxy_row:row_planet_name}</td>
<td>{group:galaxy_row:row_moon}</td>
<td>{group:galaxy_row:row_debris}</td>
<td>{group:galaxy_row:row_user}</td>
<td>{group:galaxy_row:row_ally}</td>
<td>{group:galaxy_row:row_actions}</td>
</tr>
</table>